# Generated by Django 2.0 on 2018-07-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='to_date',
        ),
        migrations.AddField(
            model_name='period',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='main.Project'),
        ),
    ]
