# Generated by Django 2.0 on 2018-07-08 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180708_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='main.Project'),
        ),
    ]
