# Generated by Django 2.0 on 2018-07-01 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listedproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='main.Project'),
        ),
    ]
